### ISSUE TITLE
MicroDrop hangs waiting for 'on_step_complete' signal from 'droplet-planning-plugin'

### ISSUE THREAD

**Issue by ryanfobel** [wheeler-microfluidics/droplet-planning-plugin#1]
From the docstring for `on_step_run`:

```python
        """
        Handler called whenever a step is executed. Note that this signal
        is only emitted in realtime mode or if a protocol is running.

        Plugins that handle this signal must emit the on_step_complete
        signal once they have completed the step. The protocol controller
        will wait until all plugins have completed the current step before
        proceeding.

        return_value can be one of:
            None
            'Repeat' - repeat the step
            or 'Fail' - unrecoverable error (stop the protocol)
        """
```

The problem seems to be caused by receiving an `on_step_swapped` signal while handling a a previous `on_step_run`. The `self.kill_running_step()` call prevents an `on_step_complete` signal from ever being sent.

```python
    def on_step_swapped(self, old_step_number, step_number):
        """
        Handler called when the current step is swapped.
        """
        logger.info('[on_step_swapped] old step=%s, step=%s', old_step_number,
                    step_number)
        self.kill_running_step()
        if self.plugin is not None:
            self.plugin.execute_async(self.name, 'get_routes')
```

# Proposed fix

Getting rid of the `self.kill_running_step()` call fixes the problem and doesn't seem to have any obvious negative impact. In general, we should think about redesigning the signaling so that these types of timing-related bugs can be avoided.

**Comment by cfobel** [comment]
What happens if the step is swapped while a route is being executed and a protocol is running?  I think the intention of the `kill_running_step` was to stop any currently executing routes when, e.g., a user clicks on a  different line in the protocol.

Are these routes still prevented from finishing if the `self.kill_running_step()` is removed?

If not, perhaps the `self.kill_running_step()` method could simply emit the `on_step_complete`?

**Comment by ryanfobel** [comment]
The problem is that processing the `on_step_swapped` before the `on_step_run` handler has finished is that you will kill the step midway, then restart it... You're right though, the user could technically click on a new step while an old one is running, in which case the previous step would keep going until finished.

I think to handle this properly, the plugin will need to retain some additional state. It needs to know that it (1) it is processing an `'on_step_run` signal and, (2) wait to process the `on_step_swapped` signal until (1) is complete. In addition it should not run the same step twice. I will try to implement something along these lines...

**Comment by ryanfobel** [comment]
I think the best way to handle this (or at least a good start) is to prevent users from changing steps while a protocol is running. See [this issue](https://github.com/wheeler-microfluidics/microdrop/issues/239).
